// Cuando se concatenan un string y un número el string siempre sale ganando como por ejemplo:

let name = 42;
let greeting = "Hi, my name is "
let mygreeting = greeting + name;
console.log(mygreeting) // se imprimirá un string

// Ahora se mostrarán algunos ejmplos del comportamiento de concatenación de strings con numeros.

console.log( 4+ 5) // 9
console.log("2" + "4") // 24
console.log("5" + 1) // 51
console.log(100 + "100") // 100100