/*

Cuando comenzamos en el mundo del desarrollo web, normalmente comenzamos por aprender a escribir 
etiquetado o marcado HTML y además, añadir estilos CSS para darle color, forma y algo de 
interacción. Sin embargo, a medida que avanzamos, nos damos cuenta que en cierta forma podemos 
estar bastante limitados.

Si únicamente utilizamos HTML/CSS, sólo podremos crear páginas «estáticas» (sin demasiada 
personalización por parte del usuario), pero si añadimos Javascript, podremos crear páginas 
«dinámicas». Cuando hablamos de páginas dinámicas, nos referimos a que podemos dotar de la 
potencia y flexibilidad que nos da un lenguaje de programación para crear documentos y páginas 
mucho más ricas, que brinden una experiencia más completa y con el que se puedan automatizar un 
gran abanico de tareas y acciones. */


// ¿Qué es el DOM? 

/*

Las siglas DOM significan Document Object Model, o lo que es lo mismo, la estructura del 
documento HTML. Una página HTML está formada por múltiples etiquetas HTML, anidadas una dentro 
de otra, formando un árbol de etiquetas relacionadas entre sí, que se denomina árbol DOM (o 
simplemente DOM).

En Javascript, cuando nos referimos al DOM nos referimos a esta estructura, que podemos 
modificar de forma dinámica desde Javascript, añadiendo nuevas etiquetas, modificando o 
eliminando otras, cambiando sus atributos HTML, añadiendo clases, cambiando el contenido de 
texto, etc...

Al estar "amparado" por un lenguaje de programación, todas estas tareas se pueden automatizar, 
incluso indicando que se realicen cuando el usuario haga acciones determinadas, como por ejemplo: 
ulsar un botón, mover el ratón, hacer click en una parte del documento, escribir un texto, etc...

*/

// El objeto document 

/* En Javascript, la forma de acceder al DOM es a través de un objeto llamado document, que 
representa el árbol DOM de la página o pestaña del navegador donde nos encontramos. En su 
interior pueden existir varios tipos de elementos, pero principalmente serán */