// CAPÍTULO 5: OPERACIONES MATEMÁTICAS BÁSICAS

//Primeramente un ejemplo

//let primeraRonda = 5;
//let segundaRonda = 10;
//let contador = primeraRonda + segundaRonda;
//console.log(contador);


/* Ejercicios:

1: Crear 2 variables referente a mi edad y el ratio de edad humano-perro*/
let miedad = 20;
let ratioHumanoPerro = 7;

// 2: Multiplicar las 2 variables y guardar el resultado en otra variable.
let edadPerro = miedad * ratioHumanoPerro;

//3: Mostrar el valor de esa variable en consola.
console.log(edadPerro + ' años');