// Create 2 variables, firstName and lastName

let firstName = "Miguel Ángel ";
let lastName = "Vitela Martínez";

// Concatenate the 2 variables into a third variable called fullName

fullName = firstName + lastName;

// Log fullName to the console

console.log(fullName)


// CONCATENATE STRINGS

let name = "Linda"
let greeting = "Hi there"

// Create a function that logs out "Hi there, Linda!" when called

function Concatenate(){
    console.log(greeting + ", " + name + "!")
}

Concatenate()