
/*También podemos asignar un valor a una variable e ir haciendo incrementos o disminuciones a ese
valor previamente asignado como lo podemos ver a continuación:*/


//let contador = 5;
//contador = contador + 1; // = 6
//contador = contador - 4; // = 2
//console.log(contador);


/* EJERCICIO

1: Crear la variable "bonusPoints" iniciarla en 50, e incrementarla a 100.
2: Bajarla a 25 y finalmente incrementarla a 70.
3: Mostrar en consola el valor de la variable despés de cada paso. */

let bonusPoints = 50;
console.log(bonusPoints);

bonusPoints = bonusPoints + 50;
console.log(bonusPoints);

bonusPoints = bonusPoints - 75;
console.log(bonusPoints);

bonusPoints = bonusPoints + 45;
console.log(bonusPoints);
